"""The whole suite, in one importable place.

The tests themselves live in tests/, one module per subject — this file is the
aggregator so that `python -m unittest test_sidecar` remains the single command
CI, the pre-commit hook, the talkwave-test skill and CLAUDE.md all name.

Run from agent-worker/:  python -m unittest test_sidecar -v

Deliberately stdlib-only (unittest, tempfile) so the venv needs nothing new.
Network is never touched.
"""

from __future__ import annotations

# Sets LOG_TO_FILE before any module that logs is imported. Must come first.
import tests  # noqa: F401

from tests.test_settings import (  # noqa: F401
    TestEverySettingIsRealAndEveryKeyIsDeclared,
    TestTheGuestDoorRuleHasOneSpelling,
    TestTheJsonStoreIdiom,
    TestTheThinkingSoundShipsOff,
    TestThePlayerOperatorSideFollowsTheMatrix,
    TestTheMapTheOperatorNavigatesBy,
    TestTheOnAirDelayIsTheOperatorsDial,
    TestTheOnAirCallerSoundSetting,
    TestTheQuietStationSetting,
    TestAConfigValueCannotNameAFileOnTheDisk,
    TestANeighbouringServiceIsNotOnLocalhost,
    TestBootLaysTheDataSkeleton,
    TestNoSettingIsSmuggledThroughTheEnvironment,
    TestOneSettingReplacingAnotherSaysSo,
    TestSettings,
    TestEverySecretRendersSomewhere,
    TestSettingsThatAreOnlyWrongTogether,
    TestTheEmbedAllowlistIsASetting,
    TestTheKeypairCanLiveInOneFile,
    TestTheDataDirCheckCannotStopTheWorker,
    TestTheProviderTablesAgreeWithEachOther,
    TestTheModelWarmedIsTheModelUsed,
    TestTurnTakingDelaysAreOptOut,
    TestTurnTakingSettingsReachTheCall,
    TestUploadedSoundsCannotFillTheVolume,
    TestTheGuestExpiryMovedToHoursWithoutMovingAnyonesExpiry,
    TestAnUpgradeClosesNoDoorAndHandsOutNoPower,
    TestACommentedEnvValueIsNamedAtBoot,
    TestTheStationPlayerShipsOff,
    TestTheCountAndHeartShipOn,
    TestTheOnAirLetterRidesTheRoomName,
    TestTheOnAirQuickKillsShipOpen,
)
from tests.test_secrets_and_auth import (  # noqa: F401
    TestAdminAuth,
    TestAnUnreadablePasswordStoreFailsClosed,
    TestFirstRunIsNotOpenToTheWeb,
    TestFrontDoorPolicy,
    TestSecrets,
    TestStoredKeysStayHome,
    TestWrittenFilesGetExplicitModes,
)
from tests.test_http import (  # noqa: F401
    TestThePlayerRelayForwardsWhatItObserved,
    TestAMissingModelNamesTheOnesTheServerHas,
    TestAStandingOverrideIsVisibleAndClearable,
    TestAnEmptyRoomIsNotAFaultWhenCallersTuneIn,
    TestCallFeedbackRejectsGarbageRoomsCheaply,
    TestListenerSamplesAreHonest,
    TestAnUnsignedWebhookCannotFillMemory,
    TestCallerIdentityCannotBeChosen,
    TestCallerIdentitySurvivesTwoProxies,
    TestTheAuthLockoutKeyIsUnspoofable,
    TestAPasswordAttemptCannotChooseItsOwnLockoutBucket,
    TestHttpSurface,
    TestJoinTokensExpire,
    TestTheModelListFollowsTheEndpoint,
    TestUsageControls,
    TestTheSettingsGearIsForTheOperator,
    TestTheOnAirDoorIsGatedAtTheMint,
    TestTheMintGivesTheWorkerAHeadStart,
)
from tests.test_widget import (
    TestSectionTagsCanShowTheirState,  # noqa: F401
    TestThePanelKeepsItsOwnRules,
    TestThePanelStylesStayOffTheCallPage,
    TestTheMusicComesBackAfterACall,
    TestNothingIsReachableOnlyByRecognisingIt,
    TestThePanelSaysWhereThingsAre,
    TestTheCallerIsNotRescuedMidAnnouncement,
    TestTheCardOnlyOffersDoorsTheTierOpens,
    TestTheStationPlayerKnowsItsPlace,
    TestAHostThemeIsADefaultNotADecree,
    TestAssetVersioning,
    TestASkinCannotReachPastItsTokens,
    TestASkinCannotLoseTheStateChannel,
    TestTheCornerControlsAreAllOneSize,
    TestWhoYouAreTalkingToDoesNotChangeUnderYou,
    TestTheDoorsSitWhereTheOperatorPutThem,
    TestEverySkinOfferedActuallyExists,
    TestTheFinderIsNotAUsernameField,
    TestTheCallPageOffersFirstRunSetup,
    TestDiagnosticsResultsKeepTheirScrollSkin,
    TestTheEmbedSitsFlushByDefault,
    TestThumbsArePerDoor,
    TestEachSurfaceIsAnsweredDeliberately,
    TestPanelLoadsOnOpen,
    TestEveryNotificationLeadsSomewhereReal,
    TestPanelMarkup,
    TestPushToTalkIsPerSurfaceAndOnByDefault,
    TestSigningInClimbsTheTier,
    TestNoStyleUsesAnUndefinedToken,
    TestTheCardIsOnlyEverInOneMode,
    TestEveryDoorReadsForItself,
    TestTheDoorsShareTheRowEvenly,
    TestTheLockedPanelShowsNothingButTheGate,
    TestTheTextLineIsShapedForTyping,
    TestTheAskMenuOffersEveryPermission,
    TestSoundPacks,
    TestTheCallButtonSaysWhatTheOperatorChose,
    TestTheCallButtonSurvivesTheUpgrade,
    TestTheCallerCanChooseWhichWayOut,
    TestTheCardIsOneHeightAndStaysThere,
    TestThePreviewCannotDisagreeWithTheCard,
    TestTheServiceWorkerStaysOutOfTheWay,
    TestTheStationsOwnColoursReachTheCard,
    TestTheWidgetActuallyParses,
    TestTheStatusChipDescribesTheCallNotTheSDK,
    TestWidgetServerContract,
    TestThePaletteTravelsForTheCycle,
    TestTheListenersVolumeIsTheirOwn,
    TestAVoicemailOnlyLineHasOneDoor,
    TestTheEmbedIsJustTheCard,
    TestTheKillSwitchOutranksEveryDoor,
    TestTheLauncherIsAPhoneInThePocket,
    TestTheEffectHasADial,
    TestThePanelReadsAtAGlance,
    TestTheBeepIsPreviewableAndWavOnly,
    TestHiddenActuallyHides,
    TestTheStylesheetParsesToTheEnd,
    TestTheUrlRowsOnlyExistInUrlMode,
    TestTheCardOffersTheCountAndTheHeart,
)
from tests.test_caller_tiers import (  # noqa: F401
    TestTheLadderLivesInOnePlace,
    TestATierIncludesTheOnesBelowIt,
    TestAnUnknownTierFailsClosed,
    TestTheDoorDecidesTheTier,
    TestUpgradingKeepsTheStationExactlyAsItWas,
)
from tests.test_call_record import (  # noqa: F401
    TestAFabricatedQueueIdIsWrittenDown,
    TestAFailedToolCallIsWrittenDown,
    TestASearchNobodyHeardTheAnswerToIsWrittenDown,
    TestASwallowedRequestIsWrittenDown,
    TestAnAskThatWentNowhereIsWrittenDown,
    TestNextPromisedFromDownTheQueueIsWrittenDown,
    TestTheRecordKeepsThePremiseItRanUnder,
    TestCallPrivacy,
    TestCallRecord,
    TestOneUtteranceIsOneLineInTheRecord,
    TestStaleRecordsCanBeThrownAway,
    TestTheFirstWordIsStampedOnce,
    TestTheCallerGetsAVerdict,
    TestTheOperatorGetsAVerdictToo,
    TestTheCallRecordHearsBothSides,
    TestTheCallRecordSaysWhoRang,
    TestTheRecordAndItsProblemsShareOneClock,
    TestThePickupTimelineIsWrittenDown,
    TestTheDayLogRemembersActionsNotPeople,
)
from tests.test_call_flow import (  # noqa: F401
    TestTheGreetingRacesItsOwnSilence,
    TestAFinishedCallStaysFinished,
    TestAnOpenAskComesBackWithoutReasking,
    TestTheWindDownIsAMomentNotAParagraph,
    TestOneStateObjectFeedsTheReplyPath,
    TestTheLabelJudgesWhatTheLexiconsCannot,
    TestTheHushMarkerHasAnOwnerEvenWhenStartRaised,
    TestTheStationClientOutlivesTheShutdownWork,
    TestRingingRidesTheMintsHeadStart,
    TestTheBriefingStopsBeingWrongWhenTheStationMovesOn,
    TestNothingInACallOverwritesSomethingElse,
    TestASlowModelGetsRoomRatherThanFailing,
    TestTheRecordNamesWhichLegFailed,
    TestTheRecordSaysWhenTheCallerWasKeptWaiting,
    TestTheOnAirFlagIsAValueNotAPresence,
    TestAHoldAlwaysEnds,
    TestTheDuckWritesDownWhatItDid,
    TestTheAirSplitHoldsItsShape,
    TestTheGreetingWaitsForTheOnAirDJ,
    TestAPromisedActionActuallyHappens,
    TestARefusedActionIsNotReportedAsDone,
    TestEveryGeneratedTurnWaitsForTheBroadcast,
    TestTheCallerIsNotShownTheDoorTwice,
    TestATurnTheCallerHasOvertakenIsDropped,
    TestTwoOfTheDJsOwnTurnsNeverStartAtOnce,
    TestTheWordsThatOweAReceipt,
    TestACallerWhoWasNeverHeardIsToldSo,
    TestALineThatFailsToGenerateIsStillSpoken,
    TestBackgroundWorkIsNotGarbageCollected,
    TestCallReceiptCardsFollowTheLine,
    TestCallRecordTimestamps,
    TestCallStructure,
    TestTheBarReleaseEndsTheTurn,
    TestComingBackFromAirIsAnnounced,
    TestEndingACallDisconnectsTheCaller,
    TestNothingToSay,
    TestSilentCallIsRecorded,
    TestTheAirGuardHoldsTheCallDJBack,
    TestTheCloseReasonIsReadable,
    TestTheIdleClockDoesNotRunWhileTheDJIsHeldBack,
    TestTheIdleClockDoesNotRunWhileTheDJIsWorking,
    TestTheCallerIsToldSomebodyIsStillThere,
    TestNoStockPhraseIsPutInTheDJsMouth,
    TestTheGateDoesNotChatter,
    TestTheTimelineSaysWhatTheGuardCouldSee,
    TestTheCheckInDoesNotBlameTheCallerForOurOwnPause,
    TestTheCheckInDoesNotTalkOverTheCaller,
    TestTheCheckInWindowIsTheNumberTheOperatorTyped,
    TestTheSignOffIsHeardBeforeTheLineCloses,
)
from tests.test_tools_surface import (  # noqa: F401
    TestABlindCallGetsTheChatsEyes,
    TestARefusalIsACardTheDJCannotSpin,
    TestActionsAllHaveAReceipt,
    TestTheCapAnnouncesItselfAsACard,
    TestExposedSurface,
    TestStationActionResults,
    TestStationWideTools,
    TestTellingTheCallerWhenTheirSongPlays,
    TestTheDJDescribesRecordsItHasInformationAbout,
    TestTheTwoMouthsShareOneSurface,
)
from tests.test_tools_logic import (  # noqa: F401
    TestANoOpCurationDoesNotChargeOrCard,
    TestASegmentThatStoodDownIsNotReportedAsAiring,
    TestATrackAlreadyWaitingIsOfferedNotReAdded,
    TestARefusedRequestNamesWhatDidNotHappen,
    TestTheTextLineCanSeeTheStation,
    TestAnActionReceiptPointsForward,
    TestAnUnconfirmedDeliveryDoesNotStartAClock,
    TestEveryStationRefusalShowsTheCallerACard,
    TestMainToolLogic,
    TestNativeScriptDoesNotAirSilently,
    TestTheSpeechActTreeIsTheLexiconTree,
    TestOneRequestCannotTakeTwoQueueSlots,
    TestTakingAHeartBackOff,
)
from tests.test_album_tools import (  # noqa: F401
    TestAMixCanBeUndoneByTheNameItWasGiven,
    TestAnAnthologyShelfSaysItsRealYears,
    TestTheBulkToolsRideTheirSwitch,
    TestQueueingAWholeAlbum,
    TestTheShelfIsAReadNotAnAction,
    TestQueueingAMix,
    TestTheSelfTitledAlbumFlood,
    TestAFailedReadNeverReadsAsAnEmptyLibrary,
    TestAPunctuatedFiledNameStillQueues,
    TestClearingARunFromTheQueue,
)
from tests.test_tools_logic import (  # noqa: F401
    TestAnObligationBelongsToTheCallerNotTheDJsWording,
)
from tests.test_house_rules import (  # noqa: F401
    TestEveryScenarioIsWellFormedBeforeItCostsAnything,
    TestTheWidgetHarnessOnlyDrivesLocal,
)
from tests.test_prompt_budget import (  # noqa: F401
    TestTheClosingSplitTracksItsOwnText,
    TestTheTruthBlockSplitChangedNoPromptByte,
)
from tests.test_finding import (  # noqa: F401
    TestItCannotReachPastTheSettings,
    TestItIsAModeNotAnExtraTool,
    TestTheRouterNamesItsOwnFields,
    TestNoCapabilityIsLost,
    TestNoDiscretionIsLost,
    TestTheDJIsToldWhichShelfItCameOff,
    TestTheTableIsNowAFunction,
)
from tests.test_stuck import (  # noqa: F401
    TestBeingToldYouAreWrong,
    TestItCostsNothingWhenTheCallerWasHeard,
    TestTheRealChatIsCaught,
    TestTheSameAskIsRecognised,
)
from tests.test_withheld import (  # noqa: F401
    TestNothingOfferedIsNeverCarded,
    TestRetuneFollowsTheSettings,
    TestTheMinaCallGetsCardAndTruth,
    TestThePatternsCannotDriftFromTheOffList,
)
from tests.test_music_tools import (  # noqa: F401
    TestARefusalIsNotAskedTwice,
    TestALateMatchStillReachesTheCaller,
    TestAMoodIsNotASearch,
    TestAQueuedTrackCanComeBackOut,
    TestCurrentLyricsAreARead,
    TestSearchPagesLikeTheStation,
    TestTheSearchRefusalAgreesWithThePrompt,
    TestSearchingForWhatTheCallerActuallySaid,
    TestWhatsNewInTheLibrary,
)
from tests.test_takeover import (  # noqa: F401
    TestAMissSaysWhatItDidFind,
    TestAShowIsReachableHoweverItIsSpelled,
    TestADJsNameResolvesToTheirShow,
    TestTheDJDoesNotBlameTheWeatherForItsOwnMiss,
    TestCancellingATakeover,
    TestNamingAShowTheCallerSaid,
    TestPinningAShow,
    TestTheCallerCannotDoThisAllNight,
    TestTheStationEndpointsAreTheOnesUpstreamServes,
)
from tests.test_brain import (  # noqa: F401
    TestTheDJKnowsWhenTheBroadcastIsNotNormal,
    TestTheLastCallersBusinessStaysOutOfTheBriefing,
    TestTheDJIsToldItsOwnLanguage,
    TestTheDJKnowsTheStationsShows,
    TestACallerCanBeToldNothingIsKept,
    TestBrainSplit,
    TestCallerContext,
    TestOneBadTrackCannotSwallowThePrompt,
    TestPromptAssembly,
    TestPrompts,
    TestEveryMouthSpeaksAsTheSameDJ,
    TestTheConductHarnessCannotReachTheRealStation,
    TestTheDrillsMcpReadsKeepUpWithTheRegistry,
)
from tests.test_chat import (  # noqa: F401
    TestALieAfterARefusalNeverReachesTheScreen,
    TestTheTextLineIsNotBlind,
    TestTheTextLineWritesDownWhatWentWrong,
    TestToolResultsGoBackAsText,
    TestAProviderFailureIsVisibleToTheOperator,
    TestTheLlmTestRunsTheShapeThatBreaks,
    TestAChatIsOneConversationNotAStringOfStrangers,
    TestTheReplyArrivesAtTheOperatorsPace,
)
from tests.test_conduct import (  # noqa: F401
    TestANamesakeIsNotTheSong,
    TestASpokenMixIsNotAMix,
    TestTheBrainReviewTierOneRules,
    TestBulkQueueingIsActedOnNotSoldOn,
    TestTheStationsLanguageIsNotTheDJsLanguage,
    TestTheDJSpeaksAsItselfNotAboutItself,
    TestADoubtedActionIsCheckedNotExplainedAway,
    TestActionBulletsRideTheirOwnSwitch,
    TestARefusalIsPassedOnNotNarrated,
    TestNoToolIsBuiltWithoutThePromptKnowingIt,
    TestThePromptNeverPromisesATakeoverItCannotDo,
    TestThePromptStopsClaimingRequestsCannotBeCancelled,
    TestThePromptTeachesTheDJHowToActuallyFindARecord,
    TestTriageIsStatedInOnePlace,
)
from tests.test_prompt_budget import (  # noqa: F401
    TestThePromptBudgetIsMeasurable,
    TestTheToolBlockSplitChangedNoPromptByte,
)
from tests.test_discovery import (  # noqa: F401
    TestAFailedReadNeverBecomesAFactAboutTheMusic,
    TestACompoundGenreIsAViableOption,
    TestATitleIsNotATrackId,
    TestTheFixedVocabulariesAreResolvedBeforeAnythingIsSent,
    TestBrowsingSpeaksTheStationsOwnVocabulary,
    TestDiscoveryToolsRideTheirSwitches,
    TestFindingMusicByHowItSounds,
    TestNeverPlayTracksNeverReachACaller,
    TestTheStationSpellsItsOwnGenres,
    TestTheStationsFavouritesAndItsMemory,
    TestTheStationsOwnWordsForAMiss,
)
from tests.test_curation import (  # noqa: F401
    TestBanningARecordIsTheOnePermanentThing,
    TestLikingTheTrackOnAir,
)
from tests.test_takeover import (  # noqa: F401
    TestLiftingALockIsNotLiftingSomeoneElsesTakeover,
    TestLockingTheStationToAGenre,
)
from tests.test_station import (  # noqa: F401
    TestNoIdEscapesItsPathSegment,
    TestTheDJsLanguageSurvivesTheRead,
    TestTheNeverPlayWritesAndTheGenreLock,
)
from tests.test_tools_logic import (  # noqa: F401
    TestOnlyThisDJsSegmentsCanBeRun,
)
from tests.test_speech_filter import (  # noqa: F401
    TestALineIsGradedByWhatKindOfWrongItIs,
    TestATypedToolCallNeverReachesTheSpeaker,
    TestPunctuationIsSpokenNotSpelled,
    TestSpeechFilter,
)
from tests.test_station import (  # noqa: F401
    TestARefusalNamesItsRule,
    TestBothCancelRefusalsAre409,
    TestATimingOutStationKeepsTheRightDJ,
    TestATimingOutStationKeepsTheRightVoice,
    TestABadPlaylistStaysSmall,
    TestAFailedReadSaysWhyItFailed,
    TestStationConfig,
    TestTheStationModelIsTheDJModelNotTheEmbedder,
    TestTheCardCacheHasOneHome,
    TestTheCardOnlyClaimsOnAirWithARealDJ,
    TestTheDJKnowsWhoIsInTheBoothAndWhatTheShowPlays,
    TestTheDJKnowsWhoIsListening,
    TestTheHoldMatchesHowLongTheStationWillTalk,
    TestTheLiveShowRecordSurvivesTheScheduleLookup,
    TestTheStationLogSaysWhatWasSaid,
    TestTheMintsHeadStartIsFreshOrNothing,
    TestTuneIn,
)
from tests.test_webhooks import (  # noqa: F401
    TestADevBootCannotStealTheLiveRegistration,
    TestAFailedProbeQuotesTheProvider,
    TestAProbeNamesOnlyWhatItSaw,
    TestTheAirFileRemembersWhatHappened,
    TestTheHandoffEventDoesNotOutrankTheLifecycle,
    TestTheCallerHearsTheStreamLate,
    TestADeliveredPushIsProvedRatherThanAssumed,
    TestAVoicePushAnchorsTheAirGuard,
    TestARefusedRegistrationSaysWhichFieldWasWrong,
    TestOtherWebhookRowsSurviveOurRegistration,
    TestOurPushesCarryAnAuthHeader,
    TestOurWebhookRowKeepsItsIdentity,
    TestPointingAtANewStationRegistersAgain,
    TestARowThatLooksRightAndLetsNothingInGetsReKeyed,
    TestStaleLookalikeRowsAreSurfacedNotDeleted,
    TestTheRegistrationShapeIsTheOneTheStationReads,
    TestTheRenameDoesNotOrphanTheOldRow,
    TestWeOnlyAskForEventsTheStationKnows,
)
from tests.test_voice import (  # noqa: F401
    TestABackendTooSlowToBeOnAPhoneCallSaysSo,
    TestADeclaredSampleRateIsMeasuredNotTrusted,
    TestAPersonaCanWearItsOwnEffect,
    TestAVoiceTheBackendCannotSpeakIsNotSilence,
    TestEveryAdapterTTSCallSiteMatchesItsSignature,
    TestEveryPersonaIsCheckedNotOnlyTheOneOnAir,
    TestTheHearingTestSpeaksWithARealVoice,
    TestShippedAdaptersAreWellFormed,
    TestTheSttModelIsLoadedOnceForTheWholeProcess,
    TestTheVoiceCanLiveInTheUrl,
    TestVoiceDiscoveryIsNotHardcodedToOneShape,
    TestWhatTheBackendSaidReachesTheOperator,
)
from tests.test_voicemail import (  # noqa: F401
    TestAMessageIsNeverLost,
    TestAnAnonymousMessageGetsNoMoreThanAnAnonymousCaller,
    TestAVoicemailRequestIsVisibleWhenTheCallerRingsBack,
    TestAVoicemailIsACallEntryToo,
    TestTheStudioWearsTheSameSoundDial,
    TestEachPersonaCanHaveItsOwnLine,
    TestTheMachineHasATierDoor,
    TestTheStationAnswersWhenNobodyIsOnAir,
    TestTheLineHasModes,
    TestAFreshGreetingIsBudgeted,
    TestTheCeilingActuallyHangsUp,
    TestTheBeepCanBeTheOperators,
    TestTheBeepVerdictIsVisible,
    TestTheDjOnlySpeaksOnce,
    TestTheBeepIsACueNotAGate,
    TestGreetingClipsFollowWhatTheyWereRenderedFrom,
    TestTheBeepIsRealAudio,
    TestTheMachineAnswersThroughTheRightRefusals,
    TestMasteringMakesAClipTheAirCanCarry,
    TestADraftIsHeldBrieflyAndLeavesNoOrphans,
    TestTheSoundbiteAirsWithReceipts,
    TestTheStudioGreetingIsRenderedOnceNotPerVisit,
    TestResamplingDoesNotAlias,
)
from tests.test_chat import (  # noqa: F401
    TestAChatRecordShowsWhatTheDJActuallyDid,
    TestChatActionCardsFollowTheLine,
    TestChatsEndInsteadOfAccumulating,
    TestTheFloodBrakeSurvivesAReconnect,
    TestOneAbuserIsSingledOut,
    TestTheTextLineFeelsLikeAConversation,
    TestTheTextLineHasADoor,
    TestTheTextLineIsOriginGated,
    TestTheTypedBrainIsTheSameBrainInADifferentRegister,
)
from tests.test_docs import (  # noqa: F401
    TestTheDocsKeepUpWithTheCode,
    TestTheDocsStayInThePresent,
)
from tests.test_house_rules import (  # noqa: F401
    TestEverySkillWouldActuallyLoad,
    TestTheInstallerTellsTheTruth,
    TestEveryTestClassIsAggregated,
    TestNewCodeDoesNotArriveUntested,
    TestTheParallelRunnerRunsTheSameSuite,
    TestNoFileGrowsWithoutSomebodyDeciding,
    TestNoFunctionGrowsTooComplex,
    TestTheImportLayeringHolds,
    TestEveryStoreDefaultsToTheOneDataDir,
    TestTheCallHarnessOnlyDialsLocal,
    TestTheDrillHarnessTracksTheModulesItDrives,
    TestTheDrillBuildsEveryToolTheCallDoes,
    TestTheHarnessCanBeInjectedIntoAnOlderImage,
    TestTheRetiredEvalStaysRetired,
    TestTheCommitGateIsStillWiredUp,
    TestTheLogKeepsTheLinesThatMatter,
    TestTheRoutingTableIsInOnePlace,
    TestTheSuiteIsNotQuietlyNotRunning,
    TestTheWrittenInstructionsStillDescribeTheCode,
)
from tests.test_onair import (  # noqa: F401
    TestOnAirChunksAreTokenedAndShortLived,
    TestTheRelayHoldsOneTurnBack,
    TestTheHoldIsAPromiseNotAnAccident,
    TestTheRelayObeysTheOperatorMidCall,
    TestTheRelayFallsBackOutLoud,
    TestTheBracketsOnlyAirWhenACallerDoes,
    TestTheLiveCallDoorTellsTheWorkersTruth,
    TestTheLiveSegmentLandsInsteadOfStopping,
    TestTapeModeAirsTheCallAtHangup,
    TestHeardModeOpensAtTheCallersFirstWord,
    TestQuietingClaimsBeforeItWrites,
    TestTheOperatorOutranksTheHush,
    TestQuietingNeverBlocksTheCall,
    TestTheJanitorIsTheOneRestorer,
    TestACrashedCallCannotMuteTheStation,
    TestHushMarkersAreScopedAndSafe,
    TestTheLiveVerdictTellsThePanelTheTruth,
    TestSessionWiringForHush,
)
from tests.test_tee import (  # noqa: F401
    TestTheAirGetsTheConversationInOrder,
    TestTheCallerTapRidesTheTurnBoundaries,
    TestTheDJTeeCutsOnSegments,
    TestATurnThatDoesNotAirSaysWhy,
    TestTheCallerClipWearsTheConfiguredSound,
)
from tests.test_heard import (  # noqa: F401
    TestTheWaitIsMeasuredFromWhenTheCallerStopped,
    TestTheBargeInIsMeasuredAndAlwaysReported,
    TestWhatTheCallerActuallyHeardIsKept,
    TestThePercentileDoesNotInventNumbers,
    TestAClearedSynthesisIsNotSomebodyTalkingOver,
)
from tests.test_open_lines import (  # noqa: F401
    TestAPremiseSpeaksWithoutItsMarkup,
    TestOpenLinesIsAdditive,
    TestTheDirectionsDeck,
    TestWhatTheDJIsToldAboutTheTopic,
    TestTheDJAllowlistActuallyMatches,
    TestAQuizTheDJCanActuallyMark,
    TestThePickupAsksAboutTheTopic,
    TestAnOpenLineBelongsToOneDJAndOneShow,
    TestRemindersCannotRunAway,
    TestTheShelfIsPerDJAndRandomlyDrawn,
    TestALineDoesNotOutlastItsProgramme,
    TestTwoDirectorsCannotAirTheSameThingTwice,
    TestAnUnconfirmedLineIsStillAnOpenLine,
    TestOpenLinesRefusesOutLoud,
    TestTheStationIsNeverReconfigured,
    TestTheVoicemailGreetingOnlyGrowsWhileALineIsUp,
    TestTheSignOffOnlySaysWhatItActuallyHeard,
    TestReportingBackToTheRoom,
    TestOpenLinesReachesThePanel,
    TestTheRecordLandsWhereTheOtherStateDoes,
    TestTheRecordSurvivesBothContainers,
)


if __name__ == "__main__":
    import unittest

    unittest.main(verbosity=2)
